/*++
    Copyright (c) Microsoft Corporation. All Rights Reserved.
    Copyright (c) Bingxing Wang. All Rights Reserved.
    Copyright (c) LumiaWoA authors. All Rights Reserved.

    Module Name:

        device.c

    Abstract:

        Code for handling WDF device-specific requests

    Environment:

        Kernel mode

    Revision History:

--*/

#include <internal.h>
#include <controller.h>
#include <device.h>
#include <spb.h>
#include <idle.h>
#include <hid.h>
#include <device.h>
#include <nt36xxx/ntinternal.h>
#include <report.h>
#include <touch_power/touch_power.h>
#include <device.tmh>

#ifdef ALLOC_PRAGMA
#pragma alloc_text(PAGE, OnD0Exit)
#endif

BOOLEAN
OnInterruptIsr(
    IN WDFINTERRUPT Interrupt,
    IN ULONG MessageID
)
/*++

  Routine Description:

    This routine responds to interrupts generated by the
    controller. If one is recognized, it queues a DPC for
    processing.

    This is a PASSIVE_LEVEL ISR. ACPI should specify
    level-triggered interrupts when using NovaTek 3202.

  Arguments:

    Interrupt - a handle to a framework interrupt object
    MessageID - message number identifying the device's
        hardware interrupt message (if using MSI)

  Return Value:

    TRUE if interrupt recognized.

--*/
{
    PDEVICE_EXTENSION devContext;
    NTSTATUS status;

    Trace(
        TRACE_LEVEL_ERROR,
        TRACE_REPORTING,
        "OnInterruptIsr - Entry: MessageID - %u", MessageID);

    status = STATUS_SUCCESS;
    devContext = GetDeviceContext(WdfInterruptGetDevice(Interrupt));

    //
    // Service touch interrupts.
    //
    status = Nt36xxxServiceInterrupts(
        devContext->TouchContext,
        &devContext->I2CContext,
        &devContext->ReportContext);

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_REPORTING,
            "Error servicing interrupts - 0x%08lX",
            status);
        goto exit;
    }

exit:
    return TRUE;
}

NTSTATUS
OnD0Entry(
    IN WDFDEVICE Device,
    IN WDF_POWER_DEVICE_STATE PreviousState
)
/*++

Routine Description:

    This routine will power on the hardware

Arguments:

    Device - WDF device to power on
    PreviousState - Prior power state

Return Value:

    NTSTATUS indicating success or failure

*/
{
    NTSTATUS status;
    PDEVICE_EXTENSION devContext;

    devContext = GetDeviceContext(Device);

    UNREFERENCED_PARAMETER(PreviousState);

    status = TchWakeDevice(devContext->TouchContext, &devContext->I2CContext);

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_POWER,
            "Error setting device to D0 - 0x%08lX",
            status);
    }

    return status;
}

NTSTATUS
OnD0Exit(
    IN WDFDEVICE Device,
    IN WDF_POWER_DEVICE_STATE TargetState
)
/*++

Routine Description:

    This routine will power down the hardware

Arguments:

    Device - WDF device to power off

    PreviousState - Prior power state

Return Value:

    NTSTATUS indicating success or failure

*/
{
    NTSTATUS status;
    PDEVICE_EXTENSION devContext;

    PAGED_CODE();

    devContext = GetDeviceContext(Device);

    UNREFERENCED_PARAMETER(TargetState);

    status = TchStandbyDevice(devContext->TouchContext, &devContext->I2CContext, &devContext->ReportContext);

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_POWER,
            "Error exiting D0 - 0x%08lX", 
            status);
    }

    return status;
}

NTSTATUS OpenIOTarget(PDEVICE_EXTENSION ctx, LARGE_INTEGER res, ACCESS_MASK use, WDFIOTARGET* target)
{
    NTSTATUS status = STATUS_SUCCESS;
    WDF_OBJECT_ATTRIBUTES ObjectAttributes;
    WDF_IO_TARGET_OPEN_PARAMS OpenParams;
    UNICODE_STRING ReadString;
    WCHAR ReadStringBuffer[260];

    Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "OpenIOTarget Entry");

    RtlInitEmptyUnicodeString(&ReadString,
        ReadStringBuffer,
        sizeof(ReadStringBuffer));

    status = RESOURCE_HUB_CREATE_PATH_FROM_ID(&ReadString,
        res.LowPart,
        res.HighPart);
    if (!NT_SUCCESS(status)) {
        Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "RESOURCE_HUB_CREATE_PATH_FROM_ID failed 0x%x", status);
        goto Exit;
    }

    WDF_OBJECT_ATTRIBUTES_INIT(&ObjectAttributes);
    ObjectAttributes.ParentObject = ctx->FxDevice;

    status = WdfIoTargetCreate(ctx->FxDevice, &ObjectAttributes, target);
    if (!NT_SUCCESS(status)) {
        Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "WdfIoTargetCreate failed 0x%x", status);
        goto Exit;
    }

    WDF_IO_TARGET_OPEN_PARAMS_INIT_OPEN_BY_NAME(&OpenParams, &ReadString, use);
    status = WdfIoTargetOpen(*target, &OpenParams);
    if (!NT_SUCCESS(status)) {
        Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "WdfIoTargetOpen failed 0x%x", status);
        goto Exit;
    }

Exit:
    Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "OpenIOTarget Exit");
    return status;
}

NTSTATUS
OnPrepareHardware(
    IN WDFDEVICE FxDevice,
    IN WDFCMRESLIST FxResourcesRaw,
    IN WDFCMRESLIST FxResourcesTranslated
)
/*++

  Routine Description:

    This routine is called by the PnP manager and supplies thie device instance
    with it's SPB resources (CmResourceTypeConnection) needed to find the I2C
    driver.

  Arguments:

    FxDevice - a handle to the framework device object
    FxResourcesRaw - list of translated hardware resources that
        the PnP manager has assigned to the device
    FxResourcesTranslated - list of raw hardware resources that
        the PnP manager has assigned to the device

  Return Value:

    NTSTATUS indicating sucess or failure

--*/
{
    NTSTATUS status;
    PCM_PARTIAL_RESOURCE_DESCRIPTOR res;
    PDEVICE_EXTENSION devContext;
    ULONG resourceCount;
    ULONG i;

    UNREFERENCED_PARAMETER(FxResourcesRaw);

    //EventRegisterMicrosoft_WindowsPhone_TouchMiniDriver();

    status = STATUS_INSUFFICIENT_RESOURCES;
    devContext = GetDeviceContext(FxDevice);

    //
    // Get the resouce hub connection ID for our I2C driver
    //
    resourceCount = WdfCmResourceListGetCount(FxResourcesTranslated);

    for (i = 0; i < resourceCount; i++)
    {
        res = WdfCmResourceListGetDescriptor(FxResourcesTranslated, i);

        if (res->Type == CmResourceTypeConnection &&
            res->u.Connection.Class == CM_RESOURCE_CONNECTION_CLASS_SERIAL &&
            res->u.Connection.Type == CM_RESOURCE_CONNECTION_TYPE_SERIAL_SPI)
        {
            devContext->I2CContext.I2cResHubId.LowPart =
                res->u.Connection.IdLowPart;
            devContext->I2CContext.I2cResHubId.HighPart =
                res->u.Connection.IdHighPart;

            status = STATUS_SUCCESS;
        }
    }

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_INIT,
            "Error finding CmResourceTypeConnection resource - 0x%08lX",
            status);

        goto exit;
    }

    //
    // Initialize Spb so the driver can issue reads/writes
    //
    status = SpbTargetInitialize(FxDevice, &devContext->I2CContext);

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_INIT,
            "Error in Spb initialization - 0x%08lX", 
            status);

        goto exit;
    }

    //
    // Initialize Touch Power so the driver can issue power state changes
    //
    status = PowerInitialize(FxDevice);

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_INIT,
            "Error in touch power initialization - 0x%08lX",
            status);

        goto exit;
    }

    //
    // Get screen properties and populate context
    //
    TchGetScreenProperties(&devContext->ReportContext.Props);

    //
    // Prepare the hardware for touch scanning
    //
    status = TchAllocateContext(&devContext->TouchContext, FxDevice);

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_INIT,
            "Error allocating touch context - 0x%08lX", 
            status);

        goto exit;
    }

    //
    // Configure the timer for continuous simulation on synaptics hardware that doesn't support it
    //
    status = ReportConfigureContinuousSimulationTimer(devContext->FxDevice);

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_INIT,
            "Error configuring continuous timer - 0x%08lX",
            status);

        goto exit;
    }

    //
    // Start the controller
    //
    status = TchStartDevice(devContext->TouchContext, &devContext->I2CContext);

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_INIT,
            "Error starting touch device - 0x%08lX",
            status);

        goto exit;
    }

    status = PoRegisterPowerSettingCallback(
        NULL,
        &GUID_CONSOLE_DISPLAY_STATE,
        TchPowerSettingCallback,
        devContext,
        &devContext->PoFxPowerSettingCallbackHandle
    );

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_INIT,
            "Error registering power setting callback (2) - 0x%08lX",
            status);

        goto exit;
    }

exit:

    return status;
}

NTSTATUS
OnReleaseHardware(
    IN WDFDEVICE FxDevice,
    IN WDFCMRESLIST FxResourcesTranslated
)
/*++

  Routine Description:

    This routine cleans up any resources provided.

  Arguments:

    FxDevice - a handle to the framework device object
    FxResourcesRaw - list of translated hardware resources that
        the PnP manager has assigned to the device
    FxResourcesTranslated - list of raw hardware resources that
        the PnP manager has assigned to the device

  Return Value:

    NTSTATUS indicating sucesss or failure

--*/
{
    NTSTATUS status;
    PDEVICE_EXTENSION devContext;

    UNREFERENCED_PARAMETER(FxResourcesTranslated);

    devContext = GetDeviceContext(FxDevice);

    status = PoUnregisterPowerSettingCallback(
        devContext->PoFxPowerSettingCallbackHandle
    );

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_INIT,
            "Error unregistering power setting callback - 0x%08lX",
            status);
    }

    status = TchStopDevice(devContext->TouchContext, &devContext->I2CContext);

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_PNP,
            "Error stopping device - 0x%08lX",
            status);   
    }

    status = TchFreeContext(devContext->TouchContext);

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_PNP,
            "Error freeing touch context - 0x%08lX",
            status);   
    }

    //EventUnregisterMicrosoft_WindowsPhone_TouchMiniDriver();

    //
    // DeInitialize Touch Power
    //
    status = PowerDeInitialize(FxDevice);

    if (!NT_SUCCESS(status))
    {
        Trace(
            TRACE_LEVEL_ERROR,
            TRACE_INIT,
            "Error in touch power deinitialization - 0x%08lX",
            status);
    }

    SpbTargetDeinitialize(FxDevice, &GetDeviceContext(FxDevice)->I2CContext);

    return status;
}

